[package]
name = "vm"
version = "0.1.0"
authors = ["Simon Whitehead <chemnova@gmail.com>"]

[dependencies]
rs6502 = "0.2.0"
find_folder = "0.3.0"

[dependencies.sdl2]
version = "*"
features = ["image", "ttf", "gfx"]